### PR TITLE
Fix compilation errors introduced in #1090

### LINKED ISSUE #1092: Compilation errors after merging #1090
See: https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/1091#issuecomment-663403764

### PR DESCRIPTION
**Pull request by triller-telekom**
Fixes #1092

Signed-off-by: Stefan Triller <stefan.triller@telekom.de>

### CODE REVIEW

**Comment by triller-telekom** [comment]
well...

```
Preparing merge commit (b093fe8)—Succeeded
Build merge (8d5cf53)—Succeeded (lines of code: 129.5k analyzed; 134.9k estimated)
Build master (cc83dea)—Failed with bad exit code during 'Extraction' (lines of code: 134.9k estimated)
```

The failure for master is expected, that's why this fix exists ;-)

**Comment by triller-telekom** [comment]
Closing in favor to https://github.com/zsmartsystems/com.zsmartsystems.zigbee/pull/1094
